version: '3.1'
services:
  mongo:
    container_name: mongo_container
    image: bitnami/mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: example

  mongo-express:
    container_name: mongoexp_container
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
